name: Build-Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore CleanTableTennisApp.sln
    - name: Build
      run: dotnet build CleanTableTennisApp.sln --no-restore
    - name: Test
      run: dotnet test CleanTableTennisApp.sln --no-build --verbosity normal
    - name: Publish 
      run: dotnet publish src/WebUI/WebUI.csproj --configuration Release -o artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cleantt-api-artifacts
        path: artifacts/

  deploy_dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cleantt-api-artifacts
          path: artifacts/
      - name: Display structure of downloaded files
        run: ls -R
