name: deploy-client

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Checkout build and deploy client
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - uses: Langsdorf/env-replace@v1.0.5
        with:
          file: './src/WebUI/ClientApp/src/environments/environment.prod.ts'
          match-secrets: "true"
          secrets: |
            AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
            AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload" # More info https://aka.ms/swaworkflowconfig
          app_location: "./src/WebUI/ClientApp" # location of package.json
          output_location: "./src/WebUI/ClientApp/dist"
          app_build_command: "npm run release"
