name: deploy-client

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Checkout build and deploy client
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Replace Auth0
        run: |
              sed -i 's/AUTH0_DOMAIN/${{secrets.AUTH0_DOMAIN}}/g' src/WebUI/ClientApp/src/environments/environment.prod.ts
              sed -i 's/AUTH0_CLIENT_ID/${{secrets.AUTH0_CLIENT_ID}}/g' src/WebUI/ClientApp/src/environments/environment.prod.ts
      - name: Deploy to azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload" # More info https://aka.ms/swaworkflowconfig
          app_location: "src/WebUI/ClientApp" # location of package.json
          output_location: "src/WebUI/ClientApp/dist"
          app_build_command: "npm run release"
